### ISSUE TITLE
What process should one use for pull-requests? (general to the org. repos)

### ISSUE THREAD

**Issue by kelu124** [echopen/kit-soft#16]
Quite similar to the other question on [another repo](https://github.com/echopen/medicotechnical/issues/3). What process should be used?
I see that there are direct commit to the trunk, which should not be - rather commit on the fork, creation of a pull-request, and peer-review/approval. 
What do you think?

**Comment by benchoufi** [comment]
sure you're right - I think I am going to `git revert` my stuff. It is not ideal but it will not mess up the git history

**Comment by kelu124** [comment]
Question of process -- we need to have a simple process, but a process of
review however ;)

**Comment by kelu124** [comment]
Let's open another question for the merge process - filling in with the elements we discussed yesterday, or at least to get an idea of the merge process?

**Comment by benchoufi** [comment]
yes, let's go to that

**Comment by kelu124** [comment]
On a documenté le process qqpart ?

**Comment by benchoufi** [comment]
I thought we agreed on a minimum peer review. Then put as far as possible the code under test. @hackolite just opened an issue/feature request to that end
