### ISSUE TITLE
Defining the Data format

### ISSUE THREAD

**Issue by kelu124** [echopen/kit-soft#18]
Keeping it here with ref to the profiler merge #17 -- we need to clarify the format.
We agreed upon 
1. CSV-like for raw-data regarding lines.
2. Absolute necessity to keep physic/constants in with a dict-like format as follows:
```
1 0 0 235 62
2 0 22 54 21
# Frequency: 3000000
# Angle: 60
# other comments
```

**Comment by benchoufi** [comment]
perfect, just we avoid spaces after the two points ":" ;) and after the hashtag. Besides, if any need of ramified data tree, we can follow an indentation by tabulation format

**Comment by benchoufi** [comment]
ok so I close the issue
